openapi: 3.0.1
info:
  title: 'PetHotel: Rooms Specification'
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - description: API для работы с номерами
    name: room-controller
paths:
  /rooms:
    get:
      tags:
        - room-controller
      operationId: getAllRooms
      summary: Получение списка всех номеров
      description: Получение списка всех номеров. Доступно только пользователями с ролью ROLE_BOSS или ROLE_ADMIN.
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
        - name: isVisible
          in: query
          description: >-
            True - для действующих номеров, False - для скрытых номеров (для
            юзера называются удаленные)
          required: true
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomDto'
        '400':
          content:
            application/json:
              example:
                error: '[]'
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: 'Required request header X-PetHotel-User-Id for method parameter type Long is not present'
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
        '403':
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                error: '[]'
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Объект не найден - в БД отсутствует пользователь с id, переданном в header.
          content:
            application/json:
              example:
                error: '[]'
                status: NOT_FOUND
                reason: The required object was not found.
                message: "user with id=1 is not found"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error. Все прочие неотлавливаемые исключения.
          content:
            application/json:
              example:
                error: '[]'
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error
                message: [ ]
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - room-controller
      operationId: addRoom
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRoomDto'
        required: true
      responses:
        '201':
          description: Номер добавлен
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoomDto'
        '400':
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
          content:
            application/json:
              example:
                error: '[]'
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: 'Required request header X-PetHotel-User-Id for method parameter type Long is not present'
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                error: '[]'
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Объект не найден - в БД отсутствует пользователь с id, переданном в header.
          content:
            application/json:
              example:
                error: '[]'
                status: NOT_FOUND
                reason: The required object was not found.
                message: "user with id=1 is not found"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Конфликт данных - номер с таким именем уже существует в БД.
          content:
            application/json:
              example:
                error: '[]'
                status: CONFLICT
                reason: For the requested operation the conditions are not met.
                message: 'Room with id=1 already exists'
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error. Все прочие неотлавливаемые исключения.
          content:
            application/json:
              example:
                error: '[]'
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error
                message: [ ]
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
  /rooms/{id}:
    get:
      tags:
        - room-controller
      operationId: getRoomById
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
        - $ref: '#/components/parameters/roomId'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoomDto'
        '400':
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
          content:
            application/json:
              example:
                error: '[]'
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: 'Required request header X-PetHotel-User-Id for method parameter type Long is not present'
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                error: '[]'
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Объект не найден. Получаем в 2 случаях - в БД отсутствует пользователь с id, переданном в header либо В БД отсутствует номер с id, переданном в параметрах.
          content:
            application/json:
              example:
                error: '[]'
                status: NOT_FOUND
                reason: The required object was not found.
                message: "user with id=1 is not found"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error. Все прочие неотлавливаемые исключения.
          content:
            application/json:
              example:
                error: '[]'
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error
                message: [ ]
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - room-controller
      operationId: deleteRoomById
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
        - $ref: '#/components/parameters/roomId'
      responses:
        '204':
          description: No Content
        '400':
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
          content:
            application/json:
              example:
                error: '[]'
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: 'Required request header X-PetHotel-User-Id for method parameter type Long is not present'
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                error: '[]'
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Объект не найден - в БД отсутствует пользователь с id, переданном в header.
          content:
            application/json:
              example:
                error: '[]'
                status: NOT_FOUND
                reason: The required object was not found.
                message: "user with id=1 is not found"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error. Все прочие неотлавливаемые исключения.
          content:
            application/json:
              example:
                error: '[]'
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error
                message: [ ]
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - room-controller
      operationId: updateRoom
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
        - $ref: '#/components/parameters/roomId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoomDto'
        required: true
      responses:
        '200':
          description: Номер обновлен
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoomDto'
        '400':
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
          content:
            application/json:
              example:
                error: '[]'
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: 'Required request header X-PetHotel-User-Id for method parameter type Long is not present'
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                error: '[]'
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Объект не найден - в БД отсутствует пользователь с id, переданном в header.
          content:
            application/json:
              example:
                error: '[]'
                status: NOT_FOUND
                reason: The required object was not found.
                message: "user with id=1 is not found"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Конфликт данных - номер с таким именем уже существует в БД.
          content:
            application/json:
              example:
                error: '[]'
                status: CONFLICT
                reason: For the requested operation the conditions are not met.
                message: 'Room with id=1 already exists'
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error. Все прочие неотлавливаемые исключения.
          content:
            application/json:
              example:
                error: '[]'
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error
                message: [ ]
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
  /rooms/{id}/unhide:
    patch:
      tags:
        - room-controller
      operationId: unhideRoomById
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
        - $ref: '#/components/parameters/roomId'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoomDto'
        '400':
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
          content:
            application/json:
              example:
                error: '[]'
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: 'Required request header X-PetHotel-User-Id for method parameter type Long is not present'
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                error: '[]'
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Объект не найден - в БД отсутствует пользователь с id, переданном в header.
          content:
            application/json:
              example:
                error: '[]'
                status: NOT_FOUND
                reason: The required object was not found.
                message: "user with id=1 is not found"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error. Все прочие неотлавливаемые исключения.
          content:
            application/json:
              example:
                error: '[]'
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error
                message: [ ]
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
  /rooms/{id}/hide:
    patch:
      tags:
        - room-controller
      operationId: hideRoomById
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
        - $ref: '#/components/parameters/roomId'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoomDto'
        '400':
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
          content:
            application/json:
              example:
                error: '[]'
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: 'Required request header X-PetHotel-User-Id for method parameter type Long is not present'
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                error: '[]'
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Объект не найден - в БД отсутствует пользователь с id, переданном в header.
          content:
            application/json:
              example:
                error: '[]'
                status: NOT_FOUND
                reason: The required object was not found.
                message: "user with id=1 is not found"
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error. Все прочие неотлавливаемые исключения.
          content:
            application/json:
              example:
                error: '[]'
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error
                message: [ ]
                timestamp: '2023-01-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Error'
components:
  parameters:
    requesterHeader:
      name: X-PetHotel-User-Id
      description: Id пользователя, осуществляющего запрос
      in: header
      required: true
      schema:
        type: integer
        format: int64
    roomId:
      name: id
      in: path
      description: ID номера, в отношении которого совершается действие
      required: true
      schema:
        type: integer
        format: int64
  schemas:
    Error:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
        message:
          type: string
        reason:
          type: string
        httpStatus:
          type: string
          enum:
            - 100 CONTINUE
            - 101 SWITCHING_PROTOCOLS
            - 102 PROCESSING
            - 103 EARLY_HINTS
            - 103 CHECKPOINT
            - 200 OK
            - 201 CREATED
            - 202 ACCEPTED
            - 203 NON_AUTHORITATIVE_INFORMATION
            - 204 NO_CONTENT
            - 205 RESET_CONTENT
            - 206 PARTIAL_CONTENT
            - 207 MULTI_STATUS
            - 208 ALREADY_REPORTED
            - 226 IM_USED
            - 300 MULTIPLE_CHOICES
            - 301 MOVED_PERMANENTLY
            - 302 FOUND
            - 302 MOVED_TEMPORARILY
            - 303 SEE_OTHER
            - 304 NOT_MODIFIED
            - 305 USE_PROXY
            - 307 TEMPORARY_REDIRECT
            - 308 PERMANENT_REDIRECT
            - 400 BAD_REQUEST
            - 401 UNAUTHORIZED
            - 402 PAYMENT_REQUIRED
            - 403 FORBIDDEN
            - 404 NOT_FOUND
            - 405 METHOD_NOT_ALLOWED
            - 406 NOT_ACCEPTABLE
            - 407 PROXY_AUTHENTICATION_REQUIRED
            - 408 REQUEST_TIMEOUT
            - 409 CONFLICT
            - 410 GONE
            - 411 LENGTH_REQUIRED
            - 412 PRECONDITION_FAILED
            - 413 PAYLOAD_TOO_LARGE
            - 413 REQUEST_ENTITY_TOO_LARGE
            - 414 URI_TOO_LONG
            - 414 REQUEST_URI_TOO_LONG
            - 415 UNSUPPORTED_MEDIA_TYPE
            - 416 REQUESTED_RANGE_NOT_SATISFIABLE
            - 417 EXPECTATION_FAILED
            - 418 I_AM_A_TEAPOT
            - 419 INSUFFICIENT_SPACE_ON_RESOURCE
            - 420 METHOD_FAILURE
            - 421 DESTINATION_LOCKED
            - 422 UNPROCESSABLE_ENTITY
            - 423 LOCKED
            - 424 FAILED_DEPENDENCY
            - 425 TOO_EARLY
            - 426 UPGRADE_REQUIRED
            - 428 PRECONDITION_REQUIRED
            - 429 TOO_MANY_REQUESTS
            - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
            - 451 UNAVAILABLE_FOR_LEGAL_REASONS
            - 500 INTERNAL_SERVER_ERROR
            - 501 NOT_IMPLEMENTED
            - 502 BAD_GATEWAY
            - 503 SERVICE_UNAVAILABLE
            - 504 GATEWAY_TIMEOUT
            - 505 HTTP_VERSION_NOT_SUPPORTED
            - 506 VARIANT_ALSO_NEGOTIATES
            - 507 INSUFFICIENT_STORAGE
            - 508 LOOP_DETECTED
            - 509 BANDWIDTH_LIMIT_EXCEEDED
            - 510 NOT_EXTENDED
            - 511 NETWORK_AUTHENTICATION_REQUIRED
        timeStamp:
          type: string
          format: date-time
    RoomDto:
      required:
        - id
        - number
        - isVisible
      type: object
      properties:
        id:
          description: Id номера
          type: integer
          format: int64
        number:
          description: Название номера
          maxLength: 100
          minLength: 1
          type: string
        area:
          description: Площадь номера
          minimum: 0
          type: number
          format: double
        Category:
          $ref: '#/components/schemas/CategoryDto'
        description:
          type: string
        isVisible:
          type: boolean
    NewRoomDto:
      required:
        - number
        - categoryId
      type: object
      properties:
        number:
          description: Название номера. Не должно быть пустым. Допускаются буквы, цифры, спецсимволы.
          maxLength: 100
          minLength: 1
          type: string
        area:
          description: Площадь номера
          minimum: 0
          type: number
          format: double
        categoryId:
          description: id категории номера
          type: integer
          format: int64
        description:
          description: описание номера
          maxLength: 150
          type: string
        isVisible:
          description: Параметр отображения номера (работает номер или нет)
          type: boolean
    UpdateRoomDto:
      type: object
      properties:
        number:
          description: Название номера. В случае наличия поля - не должно быть пустым. Допускаются буквы, цифры, спецсимволы.
          maxLength: 100
          minLength: 1
          type: string
        area:
          description: Площадь номера
          minimum: 0
          type: number
          format: double
        categoryId:
          description: id категории номера
          type: integer
          format: int64
        description:
          description: описание номера
          type: string
    CategoryDto:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID категории
          example: 1
        name:
          maxLength: 20
          minLength: 1
          type: string
          uniqueItems: true
          description: Название категории
          example: Номер для собак
        text:
          maxLength: 2500
          description: Название категории
          example: Номер для собак, антивандальная отделка, оснащен лежаками, мисками.

