openapi: 3.0.1
info:
  title: 'PetHotel: Categories Specification'
  description: Документация раздела по работе с категориями номеров
  version: v1
servers:
  - url: http://localhost:8080
    description: Local server for develop
  - url: http://212.109.192.9:8080
    description: Удалённый backend сервер для тестирования и работы frontend.
      По вопросам работы сервера обращаться к Руслану
tags:
  - description: API для работы с категориями номеров.
    name: category-controller
paths:
  /categories:
    get:
      tags:
        - category-controller
      operationId: getAllCategories
      description: Получение списка всех категорий номеров. Доступно только для пользователей с ролью BOSS или ADMIN.
      summary: Получить список всех категорий номеров
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDto'
        400:
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
          content:
            application/json:
              example:
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: "Required request header X-PetHotel-User-Id for method parameter type Long is not present"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Объект не найден - в БД отсутствует пользователь с id, переданном в header.
          content:
            application/json:
              example:
                status: NOT_FOUND
                reason: The required object was not found.
                message: "User with id=2 is not found"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Внутренняя ошибка сервера.
          content:
            application/json:
              example:
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error.
                message: [ ]
                timestamp: 2023-12-03 09:10:55
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - category-controller
      operationId: addCategory
      description: Добавление новой категории номеров.
        Доступно только пользователям BOSS и ADMIN.
      summary: Добавить новую категорию номеров
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCategoryDto'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CategoryDto'
        400:
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
          content:
            application/json:
              example:
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: "Required request header X-PetHotel-User-Id for method parameter type Long is not present"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Объект не найден - в БД отсутствует пользователь с id, переданном в header.
          content:
            application/json:
              example:
                status: NOT_FOUND
                reason: The required object was not found.
                message: "User with id=2 is not found"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        409:
          description: Ошибка уникальности полей базы данных.
          content:
            application/json:
              example:
                status: CONFLICT
                reason: integrity constraint has been violated.
                message: "Attempt to insert duplicate key row in object category with unique index name_category."
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Внутренняя ошибка сервера.
          content:
            application/json:
              example:
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error.
                message: [ ]
                timestamp: 2023-12-03 09:10:55
              schema:
                $ref: '#/components/schemas/Error'
  /categories/{id}:
    get:
      tags:
        - category-controller
      operationId: getCategoryById
      description: Получение категории номеров по ID.
        Доступно только пользователям BOSS и ADMIN.
      summary: Получить информацию о категории номеров
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
        - $ref: '#/components/parameters/categoryId'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CategoryDto'
        400:
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
          content:
            application/json:
              example:
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: "Required request header X-PetHotel-User-Id for method parameter type Long is not present"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Объект не найден - в БД отсутствует пользователь с id, переданном в header либо категория номеров с переданным ID.
          content:
            application/json:
              example:
                status: NOT_FOUND
                reason: The required object was not found.
                message: "User with id=2 is not found"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Внутренняя ошибка сервера.
          content:
            application/json:
              example:
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error.
                message: [ ]
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - category-controller
      operationId: deleteCategoryById
      description: Удаление существующей категории номеров. Доступно только пользователям BOSS и ADMIN.
      summary: Удалить информацию о категории номеров (безвозвратно)
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
        - $ref: '#/components/parameters/categoryId'
      responses:
        '204':
          description: No Content
        400:
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
          content:
            application/json:
              example:
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: "Required request header X-PetHotel-User-Id for method parameter type Long is not present"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Объект не найден - в БД отсутствует пользователь с id, переданном в header либо категория номеров с переданным ID.
          content:
            application/json:
              example:
                status: NOT_FOUND
                reason: The required object was not found.
                message: "User with id=2 is not found"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Внутренняя ошибка сервера.
          content:
            application/json:
              example:
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error.
                message: [ ]
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - category-controller
      operationId: updateCategoryById
      description: Редактирование существующей категории номеров. Доступно пользователям BOSS и ADMIN.
      summary: Изменить информацию об имеющейся категории номеров
      parameters:
        - $ref: '#/components/parameters/requesterHeader'
        - $ref: '#/components/parameters/categoryId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCategoryDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CategoryDto'
        400:
          description: Запрос составлен некорректно.Например, переданы невалидные данные.
          content:
            application/json:
              example:
                status: BAD_REQUEST
                reason: Incorrectly made request.
                message: "Required request header X-PetHotel-User-Id for method parameter type Long is not present"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: У пользователя с данной ролью нет прав на совершение данного действия.
          content:
            application/json:
              example:
                status: FORBIDDEN
                reason: Operation is denied for this user.
                message: "User with role=ROLE_FINANCIAL, can't access for this action"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Объект не найден - в БД отсутствует пользователь с id, переданном в header либо категория номеров с переданным ID.
          content:
            application/json:
              example:
                status: NOT_FOUND
                reason: The required object was not found.
                message: "User with id=2 is not found"
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        409:
          description: Ошибка уникальности полей базы данных.
          content:
            application/json:
              example:
                status: CONFLICT
                reason: integrity constraint has been violated.
                message: "Attempt to insert duplicate key row in object owner with unique index user_email."
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Внутренняя ошибка сервера.
          content:
            application/json:
              example:
                status: INTERNAL_SERVER_ERROR
                reason: Internal Server Error.
                message: [ ]
                timestamp: 2023-01-01 00:00:00
              schema:
                $ref: '#/components/schemas/Error'
components:
  parameters:
    requesterHeader:
      name: X-PetHotel-User-Id
      description: Id пользователя осуществляющего запрос
      in: header
      required: true
      schema:
        type: integer
        format: int64
    categoryId:
      name: id
      in: path
      description: ID категории номеров, в отношении которой совершается действие
      required: true
      schema:
        type: integer
        format: int64
  schemas:
    Error:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
        message:
          type: string
        reason:
          type: string
        httpStatus:
          type: string
          enum:
            - 100 CONTINUE
            - 101 SWITCHING_PROTOCOLS
            - 102 PROCESSING
            - 103 EARLY_HINTS
            - 103 CHECKPOINT
            - 200 OK
            - 201 CREATED
            - 202 ACCEPTED
            - 203 NON_AUTHORITATIVE_INFORMATION
            - 204 NO_CONTENT
            - 205 RESET_CONTENT
            - 206 PARTIAL_CONTENT
            - 207 MULTI_STATUS
            - 208 ALREADY_REPORTED
            - 226 IM_USED
            - 300 MULTIPLE_CHOICES
            - 301 MOVED_PERMANENTLY
            - 302 FOUND
            - 302 MOVED_TEMPORARILY
            - 303 SEE_OTHER
            - 304 NOT_MODIFIED
            - 305 USE_PROXY
            - 307 TEMPORARY_REDIRECT
            - 308 PERMANENT_REDIRECT
            - 400 BAD_REQUEST
            - 401 UNAUTHORIZED
            - 402 PAYMENT_REQUIRED
            - 403 FORBIDDEN
            - 404 NOT_FOUND
            - 405 METHOD_NOT_ALLOWED
            - 406 NOT_ACCEPTABLE
            - 407 PROXY_AUTHENTICATION_REQUIRED
            - 408 REQUEST_TIMEOUT
            - 409 CONFLICT
            - 410 GONE
            - 411 LENGTH_REQUIRED
            - 412 PRECONDITION_FAILED
            - 413 PAYLOAD_TOO_LARGE
            - 413 REQUEST_ENTITY_TOO_LARGE
            - 414 URI_TOO_LONG
            - 414 REQUEST_URI_TOO_LONG
            - 415 UNSUPPORTED_MEDIA_TYPE
            - 416 REQUESTED_RANGE_NOT_SATISFIABLE
            - 417 EXPECTATION_FAILED
            - 418 I_AM_A_TEAPOT
            - 419 INSUFFICIENT_SPACE_ON_RESOURCE
            - 420 METHOD_FAILURE
            - 421 DESTINATION_LOCKED
            - 422 UNPROCESSABLE_ENTITY
            - 423 LOCKED
            - 424 FAILED_DEPENDENCY
            - 425 TOO_EARLY
            - 426 UPGRADE_REQUIRED
            - 428 PRECONDITION_REQUIRED
            - 429 TOO_MANY_REQUESTS
            - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
            - 451 UNAVAILABLE_FOR_LEGAL_REASONS
            - 500 INTERNAL_SERVER_ERROR
            - 501 NOT_IMPLEMENTED
            - 502 BAD_GATEWAY
            - 503 SERVICE_UNAVAILABLE
            - 504 GATEWAY_TIMEOUT
            - 505 HTTP_VERSION_NOT_SUPPORTED
            - 506 VARIANT_ALSO_NEGOTIATES
            - 507 INSUFFICIENT_STORAGE
            - 508 LOOP_DETECTED
            - 509 BANDWIDTH_LIMIT_EXCEEDED
            - 510 NOT_EXTENDED
            - 511 NETWORK_AUTHENTICATION_REQUIRED
        timeStamp:
          type: string
          format: date-time
    CategoryDto:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID категории
          example: 1
        name:
          maxLength: 20
          minLength: 1
          type: string
          description: Название категории
          example: Номер для собак
          uniqueItems: true
        description:
          type: string
          description: Описание категории
          maxLength: 250
          example: Номер для собак, антивандальная отделка, оснащен лежаками, мисками.
    NewCategoryDto:
      required:
        - name
      type: object
      properties:
        name:
          description: Название категории. Не должно быть пустым. Допускаются буквы, цифры, спецсимволы.
          maxLength: 20
          minLength: 1
          type: string
          uniqueItems: true
          example: Номер для собак
        description:
          type: string
          description: Описание категории
          maxLength: 250
          example: Номер для собак, антивандальная отделка, оснащен лежаками, мисками.
    UpdateCategoryDto:
      type: object
      properties:
        name:
          description: Название категории. В случае наличия поля - не должно быть пустым. Допускаются буквы, цифры, спецсимволы.
          maxLength: 20
          minLength: 1
          type: string
          uniqueItems: true
          example: Номер для собак
        description:
          type: string
          description: Описание категории
          maxLength: 250
          example: Номер для собак, антивандальная отделка, оснащен лежаками, мисками.

